
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = [
    "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT",
    "https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/third_party/rust_crates/supply-chain/audits.toml?format=TEXT",
]

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.4"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.83"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "3.2.25"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "3.2.25"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.cpp_demangle]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.15"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.directories-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.fd-lock]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.ittapi]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.ittapi-sys]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.26"
criteria = "safe-to-deploy"

[[exemptions.lazycell]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.148"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.mach]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.3"
criteria = "safe-to-deploy"

[[exemptions.memfd]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.5.1"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.psm]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.9.5"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.shellexpand]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.slice-group-by]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.textwrap]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.11"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.26"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unicase]]
version = "2.7.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.4.2"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.winx]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.winx]]
version = "0.36.2"
criteria = "safe-to-deploy"

[[exemptions.witx]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.wizer]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.8+zstd.1.5.5"
criteria = "safe-to-deploy"
