
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = [
    "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT",
    "https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/third_party/rust_crates/supply-chain/audits.toml?format=TEXT",
]

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.4"
criteria = "safe-to-deploy"

[[exemptions.bindgen]]
version = "0.71.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.16"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.clang-sys]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.cpp_demangle]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.15"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.directories-next]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys-next]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.fd-lock]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.foldhash]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.3"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.169"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.maybe-owned]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.openssl]]
version = "0.10.70"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.105"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.postcard]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.psm]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.rustc-hash]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.22"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.shellexpand]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.8.0"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.26"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.trait-variant]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.64"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winx]]
version = "0.36.2"
criteria = "safe-to-deploy"

[[exemptions.witx]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "7.1.0"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.10+zstd.1.5.6"
criteria = "safe-to-deploy"
