[package]
name = "ruby-wasm-assets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
hyper = { version = "0.14.27", features = ["client", "http1"] }
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
tokio = { version = "1.32.0", features = ["rt"] }
